.husky/pre-commit
.husky/pre-push
package-lock.json
package.json

협업을 원활히 하기 위해서 husky로 pre-commit, pre-push에 대한 훅을 설정했습니다.
- 커밋 전에 git add 되어있는 파일을 대상으로  `prettier --write`를 실행합니다.
- 푸쉬 전에 모든 파일 대상으로 `npm run lint`를 실행합니다.
- lint 결과에 에러가 있으면 실패합니다.
풀 받으신 후에 npm install 하시면 따로 하실건 없습니다.
Resolves: #6

husky로 pre-commit, pre-push 설정

---

src/app/signup/page.tsx
src/components/common/Input.tsx

회원가입 페이지 UI 구현입니다.
- Input 컴포넌트 추가
-  반복되고, 로그인 페이지에서도 사용해야하기 때문에 공통 컴포넌트로 분리했습니다.
- 회원가입 페이지 UI 구현
Resolves: #11

회원가입 페이지 UI 구현

---

src/app/login/page.tsx

로그인 페이지 UI 구현입니다.
- 회원가입 페이지 UI 구현
Resolves: #13

로그인 페이지 UI 구현

---

src/app/layout.tsx
src/app/premier/layout.tsx
src/app/premier/rank/page.tsx
src/app/premier/result/page.tsx
src/components/Common/box-heading.tsx
src/components/Common/content-header/content-header.tsx
src/components/main-footer/main-footer.tsx
src/components/main-header/main-header.tsx
src/components/main-header/nav-link-item.tsx
src/components/main-header/nav-link-list.tsx
src/components/main-header/nav-sub-link-list.tsx
src/components/rank/rank-item.tsx
src/components/rank/rank-table.tsx
src/components/result/date-picker.tsx
src/components/result/result-of-game.tsx
src/components/result/result.tsx
src/utils/date-helper.ts

순위 페이지 구현, 변수 리팩토링
- 순위 페이지 구현
- 코드 리뷰 사항 수정
- main footer 하단 고정

Feat: 순위 페이지 구현, 변수 리팩토링

---

package-lock.json
package.json
src/app/(league)/premier/board/page.tsx
src/app/(league)/premier/write/page.tsx
src/components/common/Input.tsx
src/components/write/editor.tsx
src/hooks/useInput.ts

게시글 작성 페이지 UI 구현
- 게시판 페이지에 글쓰기 버튼 추가
- 에디터 라이브러리로 react-quill 설치
- Input 컴포넌트에 className 병합을 위해 twMerge 사용하도록 수정
- input 관련 로직을 모으기 위해 useInput 훅 추가
- 게시글 작성 페이지 UI 구현
Resolves: #33

게시글 작성 페이지 UI 구현

---

next.config.mjs

dynamic routes가 안되어 next config 수정
- fallback rewrites 만 하도록 수정
- API 주소에 /api/ 추가
- 개발 환경일 때만 rewrites 하도록 수정  
Resolves: #36

next config 수정

---

src/app/(league)/layout.tsx
src/app/(league)/premier/board/page.tsx
src/app/(league)/premier/write/page.tsx
src/components/match/match-record.tsx

Fix: build 오류 수정

---

src/api/post/index.ts
src/api/post/posts.ts
src/api/post/use-write-post.ts
src/app/(league)/premier/write/page.tsx
src/components/write/editor.tsx
src/hooks/useLeagueName.tsx
src/types/posts.ts

게시글 작성 기능 구현
- 게시글 작성 API 파일 추가
- useMutation 반환하는 훅 추가
- 게시글 작성에 필요한 TWritePost 타입 추가
- pathname에 있는 리그이름을 반환하는 useLeagueName 훅 추가
- 에디터에 로딩 추가
WritePage에 memberId를 임시로 지정해놔서 추후 수정해야합니다.
Resolves #55

게시글 작성 기능 구현

---

src/api/post/index.ts
src/api/post/posts.ts
src/api/post/use-delete-post.ts
src/app/(league)/premier/board/[postId]/page.tsx

게시글 삭제 기능 구현입니다.
- API 추가
- 게시글에 수정, 삭제버튼 추가. 현재는 모두에게 보입니다.
Resolves: #59

게시글 삭제 기능 구현

---

src/api/post/posts.ts
src/api/post/use-get-post-list.ts
src/api/post/use-write-post.ts
src/app/(league)/premier/board/page.tsx
src/components/board/pagination.tsx
src/types/posts.ts

게시글 리스트 조회 기능 구현
- 페이지네이션을 쿼리를 이용하여 구현
- 게시글 리스트 조회 구현
- 게시글 작성 시 쿼리 무효화
Resolbes: #58

게시글 리스트 조회 기능 구현

---

src/app/(league)/laliga/board/page.tsx
src/app/(league)/premier/board/page.tsx
src/app/(league)/premier/write/page.tsx
src/components/board/pagination.tsx

빌드 오류 수정
- 삭제후 게시글 목록 가져오기
- 라리가 pagenation 컴포넌트 임시주석
- memberId 변경

Fix: 빌드 오류 수정

---

src/api/post/use-delete-post.ts
src/app/(league)/premier/board/page.tsx
src/components/board/pagination.tsx

게시글 삭제 후 로직 수정
- 게시글 삭제 후 invalidateQueries 하도록 수정
Resolves: #63

게시글 삭제 후 로직 수정

---

src/app/(league)/premier/write/page.tsx

글 작성 시 빈 값일 때 작성 안되게 수정
- 글 작성 시 빈 값일 때 return하도록 수정
Resolves: #66

글 작성 시 빈 값일 때 작성 안되게 수정

---

src/api/post/use-delete-post.ts
src/app/(league)/premier/board/page.tsx
src/app/(league)/premier/write/page.tsx
src/components/board/pagination.tsx

main 브랜치에 머지

---

src/api/league-game/league-games.ts
src/api/league-game/use-get-game-list-by-team-id.tsx
src/app/match/[leagueGameId]/page.tsx
src/components/league-game/league-game-content-item.tsx
src/components/league-game/league-game-content.tsx
src/components/league-game/league-game.tsx
src/components/league-game/service/game-list.ts
src/components/league-game/team-list.tsx
src/components/league-game/team-logo.tsx
src/types/league-games.ts

팀별 일정 및 결과 조회
- 팀별 결과 조회
- GameListService 리팩토링
- 팀별 일정 api 개발시 새로운 이슈로 개발 진행

Feat/#71 팀별 일정 및 결과 조회

---

src/api/post/posts.ts
src/api/post/use-write-post.tsx
src/app/(league)/premier/write/page.tsx

기존 게시글 작성 /post/{memberId}에서 /post로 변경
- memberId 제거
Resolves: #80

게시글 작성 api 변경

---

src/api/post/index.ts
src/api/post/posts.ts
src/api/post/use-edit-post.tsx
src/app/(league)/premier/board/[postId]/page.tsx
src/app/(league)/premier/write/page.tsx
src/components/board/post-edit-form.tsx
src/components/write/post-form.tsx
src/hooks/useInput.tsx

게시글 수정 기능 추가
- 라우팅 대신 isEditMode 상태로 게시글 수정 기능 추가
- PostForm 컴포넌트 분리
- PostEditForm 컴포넌트에 게시글 수정 로직 분리
Resolves: #74

게시글 수정 기능 추가

---

src/api/post/index.ts
src/api/post/posts.ts
src/api/post/use-edit-post.tsx
src/app/(league)/premier/board/[postId]/page.tsx
src/app/(league)/premier/write/page.tsx
src/app/globals.css
src/app/layout.tsx
src/components/board/post-edit-form.tsx
src/components/write/post-form.tsx
src/hooks/useInput.tsx
tailwind.config.ts

프론트엔드 배포위한 merge

---

package-lock.json
package.json
src/api/auth/auths.ts
src/api/auth/index.ts
src/api/auth/use-signup.tsx
src/app/signup/page.tsx
src/components/auth-form/error-message.tsx
src/components/auth-form/label.tsx
src/components/common/button.tsx
src/components/common/input.tsx
src/constants/roles.ts
src/types/auth.ts

회원가입 기능 추가
- Button에 disabled 스타일 추가
- Input에 높이 값 제거
- react-hook-form 설치
- 회원가입 기능 구현
Resolves: #93

회원가입 기능 추가

---

src/api/post/posts.ts
src/app/post/[postId]/page.tsx
src/app/post/page.tsx
src/components/post/post-item.tsx
src/types/posts.ts

API 변경사항 반영
- 타입 명시적으로, 재사용하도록 수정
- 게시판의 게시글 컴포넌트 분리
- LoadingSpinner 사용하도록 수정
- 게시글 조회에서 댓글 수 삭제
Resolves: #109

API 변경사항 반영

---

src/api/comment/comments.ts
src/api/comment/index.ts
src/api/comment/use-get-comment-list.tsx
src/app/post/[postId]/page.tsx
src/components/post/comment-item.tsx
src/components/post/comment-list.tsx
src/types/comment.ts

댓글 조회 구현
- 댓글 조회 API 변경사항 반영해서 구현
- createdAt, updatedAt 추가
Resolves: #75

Feat: 댓글 조회 구현

---

src/api/intance.ts
src/app/layout.tsx
src/app/login/page.tsx
src/app/signup/page.tsx
src/components/common/container.tsx

회원가입 반응형 구현
-  회원가입 페이지 Box 디자인 추가
- 회원가입 반응형 디자인 구현
- 모바일 Layout 조절

Feat/#118 회원가입 반응형 구현

---

src/components/main-header/profile-dropdown.tsx

타입 이름 수정
- profile-dropdown의 props 타입 이름을 ProfileDropdownProps로 수정
Resolves: #106

profile-dropdown의 props 타입 이름을 ProfileDropdownProps로 수정

---

src/components/match/match-record.tsx
src/components/player-rank/player-rank.tsx
src/components/rank/rank-header.tsx
src/components/rank/rank.tsx

시즌 변경 기능 추가, 경기 상세 정보 오류 수정
-  팀 순위 시즌 변경
- 선수 순위 시즌 변경
- 경기 상세 정보 mom 투표 오류 해결

Feat/#122 시즌 변경 기능 추가, 경기 상세 정보 오류 수정

---

src/app/profile/page.tsx
src/types/members.ts

닉네임 필드 nickname으로 수정
- 닉네임 필드 nickname으로 수정
Resolves: #132

닉네임 필드 nickname으로 수정

---

src/api/auth/use-login.tsx
src/app/login/page.tsx
src/app/profile/page.tsx
src/app/signup/page.tsx
src/hocs/withAuth.tsx
src/hocs/withoutAuth.tsx

Protected Routes 구현
- 프로필 페이지는 withAuth로 인증 있어야만 들어갈 수 있게 구현
- 로그인, 회원가입 페이지는 withoutAuth로 인증 없이만 들어가게 구현
Resolves: #134

Protected Routes 구현

---

src/components/schedule/team-list.tsx
src/hocs/withAuth.tsx
src/hocs/withoutAuth.tsx

build 에러 수정
- 제네릭 변경
- className 프리티어 수정

Fix: build 에러 수정

---

src/api/league-game/use-get-game-list-by-league-game-id-year-month.tsx
src/api/league/leagues.ts
src/api/league/use-get-all-league.tsx
src/api/league/use-get-league.tsx
src/api/league/use-get-team-list.tsx
src/api/league/use-get-team-rank.tsx
src/app/page.tsx
src/components/home/home-rank.tsx
src/components/home/premier-schedule.tsx
src/components/player-rank/player-rank.tsx
src/components/rank/rank-table.tsx
src/components/rank/rank.tsx
src/components/schedule/date-picker.tsx
src/components/schedule/schedule-content-item.tsx
src/components/schedule/schedule.tsx
src/components/schedule/team-list.tsx
src/hooks/useLeagueName.tsx
src/types/leagues.ts

리그별 아이디를 가져와 관련된 api 호출
- 경기 일정
- 팀 순위
- 메잉ㄴ 페이지
-

Feat/#145 리그별 아이디를 가져와 관련된 api 호출

---

src/api/league-game/league-games.ts
src/components/home/premier-schedule.tsx
src/components/schedule/schedule-content.tsx
src/types/schedules.ts

Fix: 특정 날짜 경기 api 호출 방식 수정

---

src/components/home/premier-schedule.tsx
src/components/match/goal-Info.tsx
src/components/match/match-header.tsx
src/components/match/match-record.tsx
src/components/schedule/schedule-content-item.tsx
src/types/schedules.ts

골정보 api 연동및 페이지 오류 수정
- 골득점 정보 반영
- 경기상세 페이지 url 파라미터 기능 수정
- 빌드 오류 수정

Feat/#153 골정보 api 연동및 페이지 오류 수정

---

src/api/league-game/league-games-types.ts
src/api/league-game/league-games.ts
src/api/league-game/use-get-game-list-by-date.tsx
src/components/home/home-rank.tsx
src/components/home/laliga-schedule.tsx
src/components/home/premier-schedule.tsx
src/components/rank/rank.tsx

홈(메인) ui, api 수정
- 홈 페이지(메인페이지) 경기 일정 api 수정
- 홈 페이지(메인페이지) box 헤딩 폰트 크기 수정

Refactor/#155 home page UI

---

src/api/auth/auths.ts
src/api/auth/use-google-login.tsx
src/app/login/page.tsx

구글 로그인 테스트를 위한 테스트 구현
- 구글 로그인 api
- 로그인 버튼
- 기존 코드 임시 주석 처리
추후 바꿔야함

Feat: 구글 로그인 테스트를 위한 테스트 구현

---

src/app/login/page.tsx
src/components/schedule/schedule-content-item.tsx

fetch가 아닌 link로 구글 로그인 url 이동
- Link로 url 이동

Feat: fetch가 아닌 link로 구글 로그인 url 이동

---

src/app/login/page.tsx

Link대신 router를 통해 빌드시 미리 라우팅안하게 설정, Todo 작성
- useRouter를 통해 라우팅 기능 수정
- Todo 주석 작성

Fix: Link대신 router를 통해 빌드시 미리 라우팅안하게 설정, Todo 작성

---

src/api/post/posts.ts
src/api/post/use-like-post.ts
src/app/post/[postId]/page.tsx

게시글 좋아요 기능 구현
- 게시글 좋아요 기능 구현
- onMutate와 onError로 optimistic update하도록 구현
- 현재 유저가 특정 게시물에 좋아요를 눌렀는 지 확인하는 필드 필요해 보임.
Resolves: #142

게시글 좋아요 기능 구현

---

src/components/write/editor.tsx

React Quill 에디터에 link 삭제
- React Quill 에디터에 link 삭제
Resolves: #169

React Quill 에디터에 link 삭제

---

.idea/inspectionProfiles/Project_Default.xml
src/api/player/players.ts
src/app/player/[slug]/page.tsx
src/components/match/formation-item.tsx
src/components/match/formation.tsx
src/components/match/goal-Info.tsx
src/components/match/match-header.tsx
src/components/match/match-record.tsx
src/components/match/match-section.tsx
src/components/player/player.tsx
src/components/rank/rank-graph.tsx
src/components/schedule/schedule-content-item.tsx
src/constants/league-game-id.ts
src/constants/league-game.ts
src/types/schedules.ts
src/utils/league-mapper.ts
src/utils/rank-graph-generate.ts

api 변경사항반영
- 팀 순위 그래프 호버시 팀 아이콘
- 경기 상태 반영
- 골 정보 선수 클릭시 선수 상세페이지이동
- 포메이션 UI구현

Feat/#166 api 변경사항반영

---

src/api/league-game/league-games-types.ts
src/api/league-game/league-games.ts
src/api/league-game/use-get-schedule-list.tsx
src/components/rank/rank-graph.tsx
src/components/schedule/schedule.tsx
src/types/schedules.ts
src/utils/rank-graph-generate.ts

팀 순위 그래프 로고 추가
- 팀 순위 그래프 로고 추가

Style/#177 팀 순위 그래프 로고 추가

---

src/components/match/lineup/lineup-player.tsx
src/components/match/lineup/lineup-table-tbody.tsx
src/components/match/lineup/lineup-table-thead.tsx
src/components/match/lineup/sub-lineup-player.tsx
src/components/match/lineup/sub-lineup-table-tbody.tsx
src/components/match/match-record-category-item.tsx
src/components/match/match-record-category.tsx
src/components/match/match-record.tsx
src/components/match/match.utils.ts

api 변경사항 반영
- 라인업 ui 설정
- 경기 상세 기록 스탯 ui 수정
- 교체 출전 로직 수전
- 데이터 누락 대비 코드 작성

Feat/#183 api 변경사항 반영

---

src/components/match/goal-Info.tsx
src/components/match/match-header.tsx

Style: 자책골 ui 적용

---

src/components/match/lineup/lineup-table.tsx
src/components/match/match-header.tsx

Style: 경기시간 수정

---

src/components/schedule/schedule-content-item.tsx
src/components/schedule/schedule-content.tsx

Style: 링크 임시 비활성화

---

src/components/home/home-post.tsx

Feat: 홈 페이지 게시판 ui 수정

---

next.config.mjs
src/components/common/Image-with-fallback.tsx
src/components/player/player-info.tsx
src/components/player/player-stat.tsx
src/components/player/player.tsx
src/types/players.ts

- 선수 상세 페이지 UI 수정
- 사용 안하는 UI 삭제
- 선수 이미지 추가

Style/#196 modify UI api
